### ISSUE TITLE
shipit_static_analysis: Problem with an automated review

### ISSUE THREAD

**Issue by emilio** [mozilla/release-services#1106] opened 2018-04-24 14:28 UTC
**MozReview URL:** https://reviewboard.mozilla.org/r/239302/

**Problem:** Reviewbot claims that the following code:

```cpp
MediaList::MediaList() = default;
```

Would be equivalent to the code I wrote:

```cpp
MediaList::MediaList()
  : mRawList(Servo_MediaList_Create().Consume())
{
}
```

Which is obviously not the case.

**Comment by garbas** [comment] 2018-05-17 09:56
ping @marco-c @La0 @jankeromnes 

/me just making sure this issue is not lost

**Comment by abpostelnicu** [comment] 2018-05-17 11:04
I've seen this elsewhere on our bot, strangely this cannot be reproduced locally. using:

`./mach static-analysis check -c=-*,modernize-use-equals-default layout/style/ServoBindings.cpp`

But the truth is I've only tried on MacOS and the bot runs of Linux, I'm gonna test it on Linux also.

**Comment by marco-c** [comment] 2018-08-28 09:44
Duplicate of #888.

**Closed by marco-c** 2018-08-28 09:44 UTC
Labels: app:staticanalysis/bot, kind:bug, status:duplicate
