### ISSUE TITLE
Problem with an automated review: Review was only sent when committing the patch, not before.

### ISSUE THREAD

**Issue by emilio** [mozilla/release-services#1754] opened 2018-12-16 23:24 UTC
**Phabricator URL:** https://phabricator.services.mozilla.com/D14604

**Problem:** The comment from reviewbot was only seen _after_ landing the patch, even though the patch was there for more than a day awaiting review.

**Comment by jankeromnes** [comment] 2018-12-17 19:53
Thanks for reporting this issue!

Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1514845 looks similar.

**Comment by emilio** [comment] 2019-01-29 17:02
It happens all the time actually :(

**Comment by marco-c** [comment] 2019-01-29 17:31
I wonder if this couldn't be due to the fact that (IIRC) at the beginning revisions are "secure" for a bit and so we don't see them.

We are using `search_diffs` to retrieve the diffs:
https://github.com/mozilla/release-services/blob/461ccce4a0853725712a9899f8c8d641f1f46285/src/pulselistener/pulselistener/listener.py#L61

We poll using `search_diffs`, storing the latest ID, then we poll again all diffs with ID > latest ID. Maybe, when we poll we don't get the "secure" revisions in the results, but we have the latest ID, so in the next poll we skip revisions that were "secure" and then turned to "normal".

This is just an idea, we have to check :)

**Comment by marco-c** [comment] 2019-01-29 17:33
> (IIRC) at the beginning revisions are "secure" for a bit

Yes, I did recall correctly: https://wiki.mozilla.org/Phabricator/FAQ#Can_I_use_Phabricator_for_patches_to_security_bugs.3F.

**Comment by Standard8** [comment] 2019-03-28 12:19
Why is this kind:enhancement rather than kind:bug? This seems a bad issue for people to be hit by.

**Comment by jfkthame** [comment] 2019-03-28 12:22
This just happened (again) in https://phabricator.services.mozilla.com/D25101 ... it's pretty annoying, tbh.

**Comment by La0** [comment] 2019-03-28 12:56
I'm working on this issue through several means:

- The [last part](https://github.com/mozilla/release-services/pull/1988) of a serie of patches to improve stability & performance is under review
- We'll soon be able to use [build plans](https://bugzilla.mozilla.org/show_bug.cgi?id=1539745) in Phabricator to report when a code review task ran... or failed.
- Last but not least, code review analysis should run on Try pretty soon, thus avoiding a lot of depencies issues we are facing now.

We have an 81% success rate over the last week according to [our dashboard](https://static-analysis.moz.tools)
Again, i'm sorry your code did not get reviewed in time. Things should get better.

**Comment by La0** [comment] 2019-03-28 13:03
@jfkthame Your [initial code review](https://static-analysis.moz.tools/#/rev/25101)  failed due to a mercurial clone taking too long in the bot.
This kind of issue will be fixed for our next release as it's adressed by the serie of patches i mentionnde.

**Comment by gijsk** [comment] 2019-03-28 13:07
Dumb question: why can't we make sure the bot also runs on revisions that switch from hidden to published states, if the revision itself is still open at that point?

**Comment by marco-c** [comment] 2019-03-28 13:09
> Dumb question: why can't we make sure the bot also runs on revisions that switch from hidden to published states, if the revision itself is still open at that point?

The problem is that when we poll Phabricator we don't see the hidden revisions at all. This particular problem (which is rare compared to the failures due to clone timeouts) will be fixed with #1989.

**Comment by gijsk** [comment] 2019-03-28 13:10
>     * Last but not least, code review analysis should run on Try pretty soon, thus avoiding a lot of depencies issues we are facing now.

IME this doesn't help much for linting. At this point, I just expect linting to run against the patches I'm reviewing on phabricator, and if there are no comments I assume that's because the linter has run and there were no issues, and I don't look for issues as part of the review. I don't then spend 10 minutes trying to find trypushes for the patch. If submitted by new contributors, often there **are** linting issues, and then their patches get backed out.

**Comment by La0** [comment] 2019-03-28 13:24
@gijsk I meant code review tasks will run using Try infrastructure; it will be transparent for users (staff or new contributors).
Right now, we have to maintain all the deps needed to run `./mach lint|static-analysis|...`, in the future we'll use the existing toolchains, thus avoiding issues

**Comment by La0** [comment] 2019-05-10 15:37
This should no happen again since the move to Try

**Closed by La0** 2019-05-10 15:37 UTC
Labels: app:pulselistener, app:staticanalysis/bot, kind:bug
