### ISSUE TITLE
shipit_static_analysis: Issue with static analaysis with the DEBUG mode

### ISSUE THREAD

**Issue by mgaudet** [mozilla/release-services#1428] opened 2018-08-24 20:36 UTC
**Phabricator URL:** https://phabricator.services.mozilla.com/D4259

**Problem:** As near as I can tell the analysis is run without `DEBUG` defined, so it reports 

```c++
    ~AutoEnterIonCompilation() {
#ifdef DEBUG
        JSContext* cx = TlsContext.get();
        MOZ_ASSERT(cx->ionCompiling);
        cx->ionCompiling = false;
        cx->ionCompilingSafeForMinorGC = false;
#endif
    }
```

As something where a trivial destructor can be provided -- which isn't correct.

**Comment by mgaudet** [comment] 2018-08-24 20:39
Oh, even weirder, the report is flatly in the wrong place too.

**Comment by mgaudet** [comment] 2018-08-24 20:41
(As in, the line number appears to be correct, but the inline comment on the diff is in the wrong place)

**Comment by marco-c** [comment] 2018-08-28 08:06
Duplicate of #836.

**Closed by marco-c** 2018-08-28 08:06 UTC
Labels: status:duplicate
