### ISSUE TITLE
Replace phabricator "dummy" merge strategy

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1377] opened 2018-08-13 15:31 UTC
...With anything else more reliable. We've 1/4 task static-analysis from Phabricator failing because of this.

Ping @jankeromnes @marco-c

**Comment by marco-c** [comment] 2018-08-20 14:38
This is a duplicate of #1214 and #1215.
@gabriel-v has written a small Python module to retrieve the base revision of a Phabricator differential, you could use it (with some minor modification to retrieve the revision from a local mercurial clone instead of hitting hg.mozilla.org).

**Closed by marco-c** 2018-08-20 14:38 UTC
Labels: app:shipit_static_analysis, kind:enhancement, status:duplicate

**Comment by marco-c** [comment] 2018-08-20 14:39
Here it is: https://github.com/mozilla/release-services/blob/master/lib/cli_common/cli_common/phabricator.py#L20.
You could add an optional argument `repo` with the path to a mercurial repo, the function could hit hg.mozilla.org if `repo` is None or use hglib if `repo` is not None.
