### ISSUE TITLE
shipit_code_coverage: Downloading artifacts fails when some tasks are still running

### ISSUE THREAD

**Issue by gabriel-v** [mozilla/release-services#1416] opened 2018-08-22 17:08 UTC
When running `shipit-code-coverage`,  some tasks come up as `running`, probably because the build didn't finish yet. I don't know if the tasks are supposed to be all finished when the `shipit-code-coverage` project runs weekly on a Sunday, but this is not the case when running locally. Here's the stack trace:

```
[nix-shell:/opt/services/src/shipit_code_coverage]$ shipit-code-coverage --cache-root /opt/services/xxx-cache/
shipit_code_coverage.codecov: Mercurial revision (revision='3b5452b3778153f6f223bb2177235835b2314eb6')
Traceback (most recent call last):
  File "/run/user/1000/tmp.Fmcgfl0Lep/bin/shipit-code-coverage", line 11, in <module>
    load_entry_point('shipit-code-coverage', 'console_scripts', 'shipit-code-coverage')()
  File "/nix/store/73c8cn88dqmv1m70ln31liwk9kqsqyxi-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/73c8cn88dqmv1m70ln31liwk9kqsqyxi-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nix/store/73c8cn88dqmv1m70ln31liwk9kqsqyxi-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/73c8cn88dqmv1m70ln31liwk9kqsqyxi-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/af8lkd59hi3n040vwafqfqpvzmkz6s7x-python3.6-python3.6-mozilla-cli-common-1.0.0/lib/python3.6/site-packages/cli_common/cli.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/opt/services/src/shipit_code_coverage/shipit_code_coverage/cli.py", line 39, in main
    c.go()
  File "/opt/services/src/shipit_code_coverage/shipit_code_coverage/codecov.py", line 133, in go
    executor.submit(self.clone_mozilla_central, self.revision)
  File "/nix/store/af8lkd59hi3n040vwafqfqpvzmkz6s7x-python3.6-python3.6-mozilla-cli-common-1.0.0/lib/python3.6/site-packages/cli_common/utils.py", line 35, in __exit__
    future.result()
  File "/nix/store/pz8nl4cnppd3p1cykshcb40mqxjd5yvy-python3-3.6.5/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/nix/store/pz8nl4cnppd3p1cykshcb40mqxjd5yvy-python3-3.6.5/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/nix/store/pz8nl4cnppd3p1cykshcb40mqxjd5yvy-python3-3.6.5/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/services/src/shipit_code_coverage/shipit_code_coverage/artifacts.py", line 102, in download_all
    if STATUS_VALUE[status] > STATUS_VALUE[prev_task['status']['state']]:
KeyError: 'running'
```

I suggest we skip downloading artifacts that aren't `exception`, `failed` or `running`, so we avoid the KeyError above and the potential downloading failures after it.

**Comment by gabriel-v** [comment] 2018-08-22 17:48
@marco-c What would be a good solution for this? We could:

- Skip them as outlined above. This will mean we will have holes in the chunk mapping and reports.
- Wait for all the tasks to finish for a few hours, and:
    - Fail if there still are unfinished tasks, or
    - Skip the remaining unfinished tasks?
- Pull the artifacts from the most recent previous revision that has them?

**Comment by rhcu** [comment] 2018-08-25 17:35
@gabriel-v Hi. I'm not sure if I understand right but in the similar case in `Firefox-code-coverage` repository we were waiting for them to finish: 
https://github.com/marco-c/firefox-code-coverage/pull/43#discussion_r200990553.

**Comment by gabriel-v** [comment] 2018-08-29 12:55
There's a number manual of retriggers of windows code coverage tasks in the push: https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&revision=3b5452b3778153f6f223bb2177235835b2314eb6&selectedJob=195271341

**Comment by marco-c** [comment] 2018-08-29 13:12
OK, so it looks like a duplicate of #1268.

**Closed by marco-c** 2018-08-29 13:12 UTC
Labels: app:shipit_code_coverage, status:duplicate
