### ISSUE TITLE
shipit_static_analysis: Incorrect reports on mozilla-implicit-constructor & modernize-use-equals-default

### ISSUE THREAD

**Issue by nnethercote** [mozilla/release-services#953] opened 2018-03-16 04:51 UTC
**MozReview URL:** https://reviewboard.mozilla.org/r/226034/diff/2#index_header

**Problem:** See https://bugzilla.mozilla.org/show_bug.cgi?id=1411469#c30, which explains the two problems.

**Comment by marco-c** [comment] 2018-03-16 10:47
CC @Abpostelnicu

**Comment by marco-c** [comment] 2018-08-28 09:49
Duplicate of #888 and #999.

**Closed by marco-c** 2018-08-28 09:49 UTC
Labels: app:staticanalysis/bot, kind:bug, status:duplicate
