### ISSUE TITLE
Problem with an automated review: modernize-use-nullptr conflicts with intentions of TimeDuration constructor from zero

### ISSUE THREAD

**Issue by karlt** [mozilla/release-services#1661] opened 2018-10-31 03:08 UTC
**Phabricator URL:** https://phabricator.services.mozilla.com/D10163#inline-43967

**Problem:**
nullptr is not the intended format for the argument here.
https://searchfox.org/mozilla-central/rev/fc3d974254660b34638b2af9d5431618b191b233/mozglue/misc/TimeStamp.h#117

**Comment by abpostelnicu** [comment] 2018-10-31 10:01
This is a duplicate of [this](https://github.com/mozilla/release-services/issues/1657).

**Closed by abpostelnicu** 2018-10-31 10:01 UTC
