### ISSUE TITLE
When we have a stack of revisions, analyze only the last one?

### ISSUE THREAD

**Issue by sylvestre** [mozilla/release-services#944] opened 2018-03-15 09:07 UTC
Here, the bot is analyzing patches one by one without applying all of them before.

For example:
https://bugzilla.mozilla.org/show_bug.cgi?id=1438839#c23
The second patch ( _Bug 1438839 - autopep8 -i --max-line-length 99 on the tools/_ ) is being analyzed without the third (  _Bug 1438839 - Fix the remaining flake8 issues by hand_ ) which fixed most of them.

**Comment by sylvestre** [comment] 2018-03-21 15:19
Not sure it is an enhancement, I would say bug.
I had to push using inbound to avoid closing the +50 incorrect defects.

**Comment by marco-c** [comment] 2018-09-26 15:17
Duplicate of #655.

**Closed by marco-c** 2018-09-26 15:17 UTC
Labels: app:staticanalysis/bot, kind:enhancement, status:duplicate
